[phases.setup]
nixPkgs = ["python311", "gcc", "g++", "cmake", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
